In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [22]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [23]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [24]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [25]:
# Create our features
X = pd.get_dummies(df, columns=['home_ownership', 'verification_status', 'issue_d', 'pymnt_plan', 
                'initial_list_status', 'next_pymnt_d', 'application_type', 'hardship_flag', 
                'debt_settlement_flag']).drop('loan_status', axis=1)

# Create our target
y = df['loan_status']
X.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,1,0,1,1,0,1,1

In [26]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [27]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=28)
Counter(y_train)

Counter({'low_risk': 51339, 'high_risk': 273})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [29]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
balanced = BalancedRandomForestClassifier(n_estimators = 100, random_state=1)
balanced.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [30]:
# Calculated the balanced accuracy score
y_pred = balanced.predict(X_test)
brf_score = balanced_accuracy_score(y_test, y_pred)
brf_score

0.788220185628393

In [31]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   50,    24],
       [ 1700, 15431]], dtype=int64)

In [32]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.68      0.90      0.05      0.78      0.59        74
   low_risk       1.00      0.90      0.68      0.95      0.78      0.62     17131

avg / total       0.99      0.90      0.68      0.94      0.78      0.62     17205

In [35]:
# List the features sorted in descending order by feature importance
importances = balanced.feature_importances_
sorted(zip(importances, X.columns), reverse=True)

[(0.09592043308114823, 'total_rec_prncp'),
 (0.05746354488675449, 'total_pymnt_inv'),
 (0.05701442106953636, 'total_rec_int'),
 (0.05359819353391642, 'last_pymnt_amnt'),
 (0.05000652272298989, 'total_pymnt'),
 (0.026554214740303506, 'int_rate'),
 (0.023287423293341408, 'issue_d_Jan-2019'),
 (0.018198540695428842, 'installment'),
 (0.017395252340631228, 'out_prncp'),
 (0.01730332324354429, 'mo_sin_old_rev_tl_op'),
 (0.01715434483152576, 'avg_cur_bal'),
 (0.016938189775162184, 'max_bal_bc'),
 (0.016795844031598454, 'mths_since_recent_inq'),
 (0.0157785511045977, 'out_prncp_inv'),
 (0.015607933921006203, 'issue_d_Mar-2019'),
 (0.015584591380752421, 'dti'),
 (0.015303567179107441, 'annual_inc'),
 (0.015246751378228066, 'total_bal_ex_mort'),
 (0.01499612251169374, 'bc_open_to_buy'),
 (0.014358031084429226, 'il_util'),
 (0.014127147627362403, 'total_bc_limit'),
 (0.013812367799543868, 'mo_sin_old_il_acct'),
 (0.013432358525450517, 'revol_bal'),
 (0.013319409250364029, 'bc_util'),
 (0.013092437276531262, 'total_il_high_credit_limit'),
 (0.012991537612085232, 'loan_amnt'),
 (0.012909577649224473, 'all_util'),
 (0.01259468165930931, 'tot_cur_bal'),
 (0.012354052600506224, 'mo_sin_rcnt_rev_tl_op'),
 (0.01179823276515359, 'tot_hi_cred_lim'),
 (0.011708336345510174, 'total_bal_il'),
 (0.011141320960833784, 'total_rev_hi_lim'),
 (0.010941967396104094, 'num_rev_accts'),
 (0.01048060272799923, 'num_il_tl'),
 (0.010178219613861669, 'open_acc'),
 (0.009851851043889243, 'num_op_rev_tl'),
 (0.009828117176006235, 'num_bc_tl'),
 (0.009764745500162835, 'inq_last_12m'),
 (0.009518327607945493, 'mths_since_recent_bc'),
 (0.009094436511108438, 'mo_sin_rcnt_tl'),
 (0.00881744076600914, 'mths_since_rcnt_il'),
 (0.008699749365545668, 'total_acc'),
 (0.008502317195466288, 'pct_tl_nvr_dlq'),
 (0.00805790890945161, 'open_act_il'),
 (0.00796758166517421, 'num_sats'),
 (0.007618389433625674, 'open_il_24m'),
 (0.007505758178315215, 'num_actv_bc_tl'),
 (0.007497212873447933, 'next_pymnt_d_May-2019'),
 (0.007150833745542349, 'num_actv_rev_tl'),
 (0.007128009651476532, 'num_tl_op_past_12m'),
 (0.007034076403516232, 'num_rev_tl_bal_gt_0'),
 (0.007000360165329804, 'inq_last_6mths'),
 (0.006801030644638225, 'acc_open_past_24mths'),
 (0.006489637367831857, 'next_pymnt_d_Apr-2019'),
 (0.0063744639440955105, 'num_bc_sats'),
 (0.006115748187456475, 'open_rv_24m'),
 (0.005974084643625471, 'mort_acc'),
 (0.005450991806658305, 'open_acc_6m'),
 (0.00544235802243662, 'issue_d_Feb-2019'),
 (0.00544098184123383, 'percent_bc_gt_75'),
 (0.005089015866101447, 'inq_fi'),
 (0.004620022635267536, 'total_cu_tl'),
 (0.0043079678484616414, 'open_rv_12m'),
 (0.004151155630698761, 'open_il_12m'),
 (0.00409060032087375, 'delinq_2yrs'),
 (0.003625215022968164, 'total_rec_late_fee'),
 (0.0034252982872860936, 'tot_coll_amt'),
 (0.0027668750547242605, 'num_accts_ever_120_pd'),
 (0.00267702420072762, 'verification_status_Verified'),
 (0.0018472253337006794, 'home_ownership_RENT'),
 (0.0018208668797456199, 'pub_rec_bankruptcies'),
 (0.0017622388532141009, 'verification_status_Not Verified'),
 (0.0017494051244559738, 'application_type_Individual'),
 (0.001688878433129695, 'verification_status_Source Verified'),
 (0.0013465546868329744, 'pub_rec'),
 (0.0011733594468049217, 'home_ownership_MORTGAGE'),
 (0.0011597575610414672, 'home_ownership_OWN'),
 (0.00097700518742361, 'num_tl_90g_dpd_24m'),
 (0.0009700309352412033, 'initial_list_status_f'),
 (0.0009346577692279697, 'application_type_Joint App'),
 (0.000711326344603032, 'initial_list_status_w'),
 (0.00041696706689147876, 'collections_12_mths_ex_med'),
 (0.00012525219621320049, 'chargeoff_within_12_mths'),
 (4.884004884004885e-05, 'home_ownership_ANY'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [36]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
easy = EasyEnsembleClassifier(n_estimators = 100,
                                     random_state=1)
easy = easy.fit(X_train, y_train)

In [37]:
# Calculated the balanced accuracy score
y_pred = easy.predict(X_test)
ensemble_score = balanced_accuracy_score(y_test, y_pred)
ensemble_score

0.9298348024049968

In [38]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   68,     6],
       [ 1015, 16116]], dtype=int64)

In [40]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.06      0.92      0.94      0.12      0.93      0.86        74
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17131

avg / total       1.00      0.94      0.92      0.97      0.93      0.87     17205